/** Render a Report as Markdown (for PR comments / CI artifacts). */

import type { Report } from "../types.js";

const ICON = { error: "✗", warning: "⚠", info: "ℹ", pass: "✓" } as const;

export function toMarkdown(report: Report): string {
  const s = report.summary;
  const out: string[] = [];
  out.push(`# actionbudget report`);
  out.push("");
  out.push(
    `**${s.score}/100 (${s.grade})** across **${s.workflows}** workflow(s) — ` +
      `${s.errors} error(s), ${s.warnings} warning(s), ${s.infos} info(s)`,
  );
  out.push("");

  for (const wf of report.workflows) {
    const title = wf.name ? `${wf.source} — ${wf.name}` : wf.source;
    out.push(`## ${title} — ${wf.score}/100 (${wf.grade})`);
    out.push("");
    if (wf.findings.length === 0) {
      out.push(`✓ No waste found.`);
      out.push("");
      continue;
    }
    out.push(`| | Rule | Where | Issue | Fix |`);
    out.push(`| - | ---- | ----- | ----- | --- |`);
    for (const f of wf.findings) {
      const where = [f.job ? `job \`${f.job}\`` : "", f.line ? `L${f.line}` : ""].filter(Boolean).join(" ");
      const fix = (f.fix ?? "").split("\n")[0]!.replace(/\|/g, "\\|");
      out.push(`| ${ICON[f.severity]} | \`${f.rule}\` | ${where} | ${f.title.replace(/\|/g, "\\|")} | ${fix} |`);
    }
    out.push("");
  }

  out.push(`---`);
  out.push(`<sub>Generated by actionbudget v${report.version} · ${report.generatedAt}</sub>`);
  out.push("");
  return out.join("\n");
}
